# site settings
title: #teamdisco
subtitle: The Bot Company
email: rob@kite9.com
description: A comic about bots, chat, ai and developers
baseurl: "/" # the subpath of your site, e.g. /blog
include: ['_pages']
#url: https://teamdisco.com
author: Rob Moffat
city: London
country: UK
phone: "+447900_247_282"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/robmoffat
linkedin_url: https://www.linkedin.com/in/robmoffat/

# build settings
markdown: kramdown

sass:
  style: compressed
